language: python
python:
  - "3.6"

sudo: false

env: 
  - Django=1.11

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'SHOW SERVER_VERSION;' -U postgres
  - psql -c 'create database test_db;' -U postgres
notifications:
  email: false

